app.factory('quizFactory', function () {
    var questions = [
        {"Id":25026,"Text":"Điều khiển được sử dụng để hiển thị nội dụng trang web trong ứng dụng Android?","Marks":1,"AnswerId":103784,"Answers":[{"Id":103783,"Text":"Button"},{"Id":103784,"Text":"WebView"},{"Id":103785,"Text":"Spinner"},{"Id":103786,"Text":"EditText"}]},{"Id":25027,"Text":"Đối với URLConnection, sử dụng phương thức nào để thiết lập timeout cho connection?","Marks":1,"AnswerId":103790,"Answers":[{"Id":103787,"Text":"setURLTimeout()"},{"Id":103788,"Text":"setInternetTimeout()"},{"Id":103789,"Text":"setTimeout()"},{"Id":103790,"Text":"setConnectTimeout()"}]},{"Id":25028,"Text":"Cho đoạn mã lệnh sau:wv.setWebChromeClient(new WebChromeClient() { @Override public void onReceivedTitle(WebView view, String title) { getWindow().setTitle(title); } });Hãy cho biết đoạn lệnh trên dùng để làm gì?","Marks":1,"AnswerId":103791,"Answers":[{"Id":103791,"Text":"Thay đổi title của trang web"},{"Id":103792,"Text":"Đóng trang web"},{"Id":103793,"Text":"Thay đổi nội dung của trang web"},{"Id":103794,"Text":"Lấy thông tin title của trang web"}]},{"Id":25029,"Text":"Sử dụng lớp nào để truy cập và thay đổi thông tin trên trình duyệt mặc định của hệ điều hành Android?","Marks":1,"AnswerId":103798,"Answers":[{"Id":103795,"Text":"WebClient"},{"Id":103796,"Text":"WebSafariClient"},{"Id":103797,"Text":"WebFirefoxClient"},{"Id":103798,"Text":"WebViewClient"}]},{"Id":25030,"Text":"Câu nào là sai đối với WebView?","Marks":1,"AnswerId":103800,"Answers":[{"Id":103799,"Text":"Không có widget cho brownser activity"},{"Id":103800,"Text":"Không thể sử dụng tag trong XML layout"},{"Id":103801,"Text":"Click vào link sẽ gọi trình duyệt"},{"Id":103802,"Text":"Có thể sử dụng tag trong XML layout"}]},{"Id":25031,"Text":"Phương thức nào của WebSettings để cho phép WebView hỗ trợ JavaScript?","Marks":1,"AnswerId":103806,"Answers":[{"Id":103803,"Text":"setJavaScriptEnabled(false)"},{"Id":103804,"Text":"setJavaScript(true)"},{"Id":103805,"Text":"setJavaScriptEnable(true)"},{"Id":103806,"Text":"setJavaScriptEnabled(true)"}]},{"Id":25032,"Text":"Khi thời gian kết nối đến một URL quá timeout, phương thức getInputStream() sẽ đưa ra ngoại lệ nào?","Marks":1,"AnswerId":103809,"Answers":[{"Id":103807,"Text":"java.net.TimeoutException"},{"Id":103808,"Text":"java.net.SocketException"},{"Id":103809,"Text":"java.net.SocketTimeoutException"},{"Id":103810,"Text":"java.net.SocketTimeout"}]},{"Id":25033,"Text":"Chương trình sử dụng WebView phải có quyền gì?","Marks":1,"AnswerId":103811,"Answers":[{"Id":103811,"Text":"android.permission.AUTHENTICATE_ACCOUNTS"},{"Id":103812,"Text":"android.permission.BIND_APPWIDGET"},{"Id":103813,"Text":"android.permission.INTERNET"},{"Id":103814,"Text":"android.permission.BIND_INPUT_METHOD"}]},
    ];

    return {
        getQuestion: function (id) {
            if (id < questions.length) {
                return questions[id];
            } else {
                return false;
            }
        }
    };
});